### ISSUE TITLE
cfg lock issues

### ISSUE THREAD

**Issue by michaeleisel** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#12]
When I run `setup_var 0x5C1 0x00`, I get `error: offset is out of range..` as shown in the picture. Is this expected? My hackintosh doesn't get past the Aorus logo screen when I have the MacOS USB stick in and I'm trying to figure out why. My steps:

- set all other BIOS settings up as per this guide
- downloaded the version of the .efi linked in this repo's readme
- formatted a USB stick to have a GUID partition map and FAT32 formatting
- moved the .efi to EFI/BOOT/bootx64.efi
- booted with just that USB stick in and ran `setup_var 0x5C1 0x00` in the shell
- observed error message

Am I supposed to run one of the variants like `setup_var_2`? Can additional auto-created files on the grub shell stick, like `System Volume Information` and `.fseventsd` cause problems? And why doesn't the guide recommend setting `AppleXcpmCfgLock` and `AppleCpuPmCfgLock` to true instead of running this command? (I also tried that but still can't boot)

![IMG_7785](https://user-images.githubusercontent.com/718607/89131192-e9dfbc80-d4d8-11ea-9211-7ab403759141.jpg)

**Comment by 123marvin123** [comment]
The value for address 0x5C1 did actually change as you can see in the log from 0x01 (active) to 0x00 (inactive) which is correct. I think I got the same messages when I setup my hackintosh, so the process was **successful**.

The AppleXcpmCfgLock and AppleCpuPmCfgLock can be used too, of course. But it is always better to just set the correct bios settings, instead of trying to let the boot loader force them.

Regarding your boot problem: Do you even have a bootloader (open core) or did you just copy GRUB to your usb disk?

**Comment by michaeleisel** [comment]
Thank you, good to know that that part is working. As for whether I have a bootloader, yes. I have two sticks, one with the .efi for cfg lock and the other with a MacOS installer plus OpenCore-ified EFI

**Comment by michaeleisel** [comment]
Ah, I got it now, indeed it was another issue. Perhaps it'd be good to have a note explaining what the expected output is for this, since all it says is that going to set it, but it never explicitly tells us it succeeded, and instead the last line is an error message.
