### ISSUE TITLE
wifi and bt is working built-in on this mobo

### ISSUE THREAD

**Issue by isyan** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#18]
I used this kexts.. https://www.tonymacx86.com/threads/success-working-intel-wifi-drivers-for-7265ac-on-catalina.292207/post-2177829

**Comment by 123marvin123** [comment]
I've been following the OpenIntelWireless project too, but it's really only at the beginning of development because of the complexity. I wouldn't recommend this over a real Airport card, since not every feature is supported. More information can be found here:

https://openintelwireless.github.io 

If you really only care about wifi and bluetooth, this might be a good alternative.
